variables:
  REPO_NAME: 'panda3d-thirdparty'

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    matrix:
      vc140-x86-release:
        ARCHITECTURE_SUFFIX: ''
        BUILD_TOOLSET_VERSION: '140'
        BUILD_CONFIGURATION: 'release'
        CMAKE_GENERATOR: 'Visual Studio 15 2017'
      vc140-x64-release:
        ARCHITECTURE_SUFFIX: '-x64'
        BUILD_TOOLSET_VERSION: '140'
        BUILD_CONFIGURATION: 'release'
        CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      vc141-x86-release:
        ARCHITECTURE_SUFFIX: ''
        BUILD_TOOLSET_VERSION: '141'
        BUILD_CONFIGURATION: 'release'
        CMAKE_GENERATOR: 'Visual Studio 15 2017'
      vc141-x64-release:
        ARCHITECTURE_SUFFIX: '-x64'
        BUILD_TOOLSET_VERSION: '141'
        BUILD_CONFIGURATION: 'release'
        CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'

  steps:
  # configure & generate
  - task: CMake@1
    inputs:
      cmakeArgs: .. -G "$(CMAKE_GENERATOR)" -Wno-dev -T "v$(BUILD_TOOLSET_VERSION),host=x64"

  # build
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config release -j4

  # tests
  #- task

  # install
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/win-libs-vc15$(ARCHITECTURE_SUFFIX)'
      targetFolder: '$(Build.BinariesDirectory)/thirdparty/win-libs-vc14$(ARCHITECTURE_SUFFIX)'

  # packaging
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/thirdparty'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/thirdparty.7z'

  # publish
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(REPO_NAME)-vc$(BUILD_TOOLSET_VERSION)$(ARCHITECTURE_SUFFIX)-$(BUILD_CONFIGURATION)'
